### ISSUE TITLE
can git-gutter support nlinum-mode?

### ISSUE THREAD

**Issue by redguardtoo** [emacsorphanage/emacs-git-gutter#124]
git-gutter runs perfectly in linum-mode.

The only issue is linum-mode itself is slower than nlium-mode.

**Comment by syohex** [comment]
I don't understand well nlinum-mode. I try to understand it and support it.

**Comment by redguardtoo** [comment]
Some user reported he's code file could contain 20000 lines.

In this case, he has to turn off `linum-mode`.

I suggest avoid displaying signs when `linum-mode` is off but keep other non-visual functionality.

Although I'm heavy git-gutter user, I don't check visual signs now. I usually just jump to closest hunk.

**Comment by syohex** [comment]
See #130.

**Comment by zw963** [comment]
`(linum-mode)` performance loss problem is exist so long ...

here is a [issue](https://github.com/emacs-helm/helm/issues/1550) I just create for helm. 

though, those problem is somelike not caused by helm, just linum-mode and another package.

I switch from `linum-mode` to `nlinum-mode` just now,  performance better.
if file is larger, it maybe have a great improved.

**Comment by zw963** [comment]
@redguardtoo ,  your's nlium-mode is worked with `emacsclient` ?

It worked with emacs, but not worked with daemon mode.
my emacs version is 24.5.1
when connect to emacs server with `emacsclient -nc one_file`, get 
```sh
*ERROR*: Invalid face: linum
```

**Comment by zw963** [comment]
following piece code worked for me.
```
(defun initialize-nlinum (&optional frame)
  (require 'nlinum)
  (add-hook 'prog-mode-hook 'nlinum-mode))
(when (daemonp)
  (add-hook 'window-setup-hook 'initialize-nlinum)
  (defadvice make-frame (around toggle-nlinum-mode compile activate)
  (nlinum-mode -1) ad-do-it (nlinum-mode 1)))
```
Those code make my emacs 24.5.1 daemon mode worked with nlinum-mode
 very well.  No matter what open a frame from terminal or create a new frame in emacs.

**Comment by tigerk0430** [comment]
any progress so far? 
I tried to use `git-gutter-mode` with `nlinum-mode` but those are not combined clearly ;-(

**Comment by zw963** [comment]
I thought this is not a issue any more for Emacs 26, please consider use "display-line-numbers-mode", it's more quickly, and work well with git-gutter.

**Comment by tigerk0430** [comment]
@zw963 
Thank you, I'll use it

**Comment by syohex** [comment]
I apologize my late reply.

This package is no longer maintained. If you want to add new features, please fork and use it.

**Comment by zw963** [comment]
thank you.
