### ISSUE TITLE
Not worked with linum-mode when scroll page.

### ISSUE THREAD

**Issue by zw963** [emacsorphanage/emacs-git-gutter#127]
When enable linum-mode, emas-git-gutter is seem like worked.

But, when I page up and back again,  git-gutter sign is missing.
only change buffer again, those sign reappear again.

following is my config, I test it in emacs 24.5 with emacs -Q and use emacs X GUI.

``` cl
(require 'git-gutter)
(with-eval-after-load 'linum-mode (git-gutter:linum-setup))
;; global options for git-gutter
(setq
 git-gutter:diff-option "-w"
 git-gutter:hide-gutter t
 git-gutter:ask-p nil                   ;don't ask when stage/revert
 git-gutter:update-interval 0.1           ;默认 0 异步的升级 diff 信息.
 )

;; git-gutter options
(setq
 git-gutter:window-width 1
 git-gutter:modified-sign " "      ;default ==
 git-gutter:added-sign " "         ;default ++
 git-gutter:deleted-sign " "       ;default --
 )

(add-hook 'prog-mode-hook 'git-gutter-mode)
```

**Comment by syohex** [comment]
It is difficult to work with linum-mode well. I recommend you to use diff-hl, if you use linum mode.

**Comment by zw963** [comment]
`diff-hl` missing a critical feature for me, stash current hunk change.

because i use emacs only with GUI mode, so i will keep use git-gutter-fringe, 
hope that repo is keep update. thanks.

**Comment by syohex** [comment]
I apologize my late reply. This package is no longer maintained. If you want to support linum-mode well, please fork and implement it.

**Comment by zw963** [comment]
thank you.
