### ISSUE TITLE
support 3rd party VCS

### ISSUE THREAD

**Issue by redguardtoo** [emacsorphanage/emacs-git-gutter#140]
I'm forced to use perforce right now. It's a pain I can't use git-gutter with perforce.

I understand It doesn't make sense that git-gutter supports all those propriety VCS.

But a simple and general solution should be enough for me. This solution needs one global variable and one command.

1. `(defvar git-gutter-exp-to-create-diff-for-other-vcs nil)` This variable could be a string, an expression, a function, if it's a string, it will be the parameter passed to `shell-command-to-string`; if expression, it's expected the expression will be evaluated and return a string; if function, it will be executed and return a string. String is expected to be in patch format

2. `(defun git-gutter-show-gutters-for-other-vcs () ...)` shows gutters according to evaluation of above variable.

**Comment by syohex** [comment]
This is interesting. I'll try to design and implement supporting 3rd party VCS feature. But sorry I have no time for a while(1 or 2 week).

**Comment by redguardtoo** [comment]
Thanks. No rush for the implementation.

Code for point 1,
```lisp
(cond
 ;; shell command
 ((stringp backend)
  (ffip-show-content-in-diff-mode (shell-command-to-string backend)))
 ;; command
 ((functionp backend)
  (ffip-show-content-in-diff-mode (funcall backend)))
 ;; lisp exipression
 ((consp backend)
  (ffip-show-content-in-diff-mode (funcall `(lambda () ,backend)))))
```

**Comment by syohex** [comment]
This package is no longer maintained. If you want to add new feature. Please fork and use it
