### ISSUE TITLE
Text Moves to the Right with linum-mode

### ISSUE THREAD

**Issue by naclander** [emacsorphanage/emacs-git-gutter#143]
Hello, I commented on the [old issue](https://github.com/syohex/emacs-git-gutter/issues/116), but I figured it was a good idea to open a new one.

As of right now ( commit `1590127335cef06af8d77884f9c16a8629d65943` on `master` ) I am getting the same behavior as described in the original issue. Test keeps moving to the right ( until i can no longer do so ) when using linum-mode ( specifically global-linum-mode) and git-gutter-mode. 

I have` (git-gutter:linum-setup)` in my config.

This does not happen to me when using emacs25, so it might be in an upcoming patch. I have not tried this on the latest RC. 

I have tried using git-gutter on nlinum-mode, but I see that support is still an [open issue](https://github.com/syohex/emacs-git-gutter/issues/124)

**Comment by naclander** [comment]
FYI, I don't care about this issue anymore as (n)linum-mode has been deprecated in favor of the built-in emacs line numbering system.

**Comment by innerout** [comment]
In which version of emacs linum got deprecated and how you use the new system it would be helpful to know.I am in version 25.1.I know the new numbering mode is live only for master branch that is version 27.

**Comment by seagle0128** [comment]
The Emacs26 has a built-in `line-number-mode` written by C.

**Comment by innerout** [comment]
Also Emacs26  supports global-display-line-numbers-mode instead of the linum-mode.But the problem is that git-gutter is not working over it.

**Comment by arichiardi** [comment]
Stumbled upon this problem and I see the solution is very nice indeed, thanks, will use `global-display-line-numbers-mode`!

**Comment by josephgrossberg** [comment]
Thank you for this thread -- very helpful!

Here's the change I made in my `.emacs`, to fix this issue:

```diff
-(git-gutter:linum-setup)
-(global-linum-mode t)
+(global-display-line-numbers-mode t)
```

**Comment by syohex** [comment]
Sorry very late reply. This package is no longer maintained.

IMO: I never use linum-mode and it is difficult to support it and I got stressed from it.
