### ISSUE TITLE
Git Gutter don't notice changes in whitespaces, while Git do

### ISSUE THREAD

**Issue by ReneFroger** [emacsorphanage/emacs-git-gutter#147]
For example, I have the following code:

`foo bar`

I change the one space between `foo` and `bar` into two spaces:

`foo  bar`

With `git diff` I see the changes. But there is no indicator in fringe from Git-Gutter to indicate that the line is changed. Seems a bug to me, given the opinion that git-diff should be the leading indicator?

**Comment by syohex** [comment]
I apologize my late reply.

This package is no longer maintained.

IMO: I cannot reproduce this issue.
