### ISSUE TITLE
cripples TRAMP performance

### ISSUE THREAD

**Issue by aspiers** [emacsorphanage/emacs-git-gutter#151]
When git-gutter is enabled, loading remote files with TRAMP via ssh results in terrible performance, because it causes TRAMP to constantly reopen fresh ssh connections.  (The minibuffer and TRAMP's debug buffer show `Waiting for prompts from remote shell`).

I switched to https://github.com/nonsequitur/git-gutter-plus and it fixed the issue.

**Comment by syohex** [comment]
Sorry very late reply. This package is no longer maintained.

**Comment by syohex** [comment]
Sorry my  irresponsibly response. However I dislike TRAMP because I never use it and it makes elisp code very complicated. If you resolve this issue by using git-gutter-plus, I suppose you use it instead of this package.

**Comment by Atemu** [comment]
Unfortunately, this is still an issue. Is it possible to disable git-gutter in TRAMP connections only?

**Comment by raxod502** [comment]
I've accomplished that by adding an `:around` advice to `git-gutter--turn-on` in my personal configuration, see https://github.com/radian-software/radian/pull/563.
