### ISSUE TITLE
Add mode map

### ISSUE THREAD

**Issue by Wilfred** [emacsorphanage/emacs-git-gutter#161]
Currently git-gutter-mode has no git-gutter-mode-map, which makes it impossible to define keys that only work when git-gutter is active.

**Comment by syohex** [comment]
I apologize my late reply. This package is no longer maintained. If you want to add such feature, please fork this repository and use it.

IMO: Such key map is not necessary because I suppose git-gutter is enabled as global-mode and those commands should be set global-key-map.
