### ISSUE TITLE
Project status and maintenance

### ISSUE THREAD

**Issue by ramnes** [emacsorphanage/emacs-git-gutter#169]
Hey community,

I hate to be that guy, but it is obvious that @syohex isn't maintaining this project anymore, nor any other. The package is very popular though, with more than 290K downloads on MELPA.

There are currently 10 pull requests that are awaiting to be merged, or at least discussed, and while @nonsequitur created [git-gutter-plus](https://github.com/nonsequitur/git-gutter-plus) to include some (all?) of these, it doesn't seem maintained anymore either.

That would be awesome that we could rely on a single fork to be kept maintained over time. Alas, I'm not able to step in as a maintainer myself these days; is there anyone that would be ready to take the position?

Thanks for reading. You can now enjoy this [relevant song](https://www.youtube.com/watch?v=MbXWrmQW-OE).

**Comment by gonewest818** [comment]
Hello Guillaume,

A group of folks discussing over here:  https://github.com/melpa/melpa/issues/6674

With the author's permission, the MELPA maintainers are working to find new maintainers for his emacs projects. I've volunteered to take on this package and a few others, although final assignment has yet to be determined

thanks

**Comment by ramnes** [comment]
Awesome, thank you @gonewest818. Let's hope that @syohex ends up answering there and migrating every repository to @emacsorphanage.

I'll keep that issue open for curious people.

**Comment by ramnes** [comment]
It happened! :tada: 

Thank you so much @syohex!
