### ISSUE TITLE
Segfault when scrolling

### ISSUE THREAD

**Issue by ch3pjw** [emacsorphanage/emacs-git-gutter#75]
On latest (0.79, SHA: 07cab97), using in conjunction with `linum-mode` in a tty, if I scroll up and down repeatedly, I get a segfault from `GNU Emacs 24.3.1`. I'm literally just starting out with `emacs`, so I don't know exactly what further information is going to be useful to you!

My `~/.emacs.d/init.el` contains

```
(add-to-list 'load-path "~/.emacs.d/emacs-git-gutter")
(require 'git-gutter)
(global-git-gutter-mode +1)           
```

I'm also using `viper`, `evil` and `go-mode`.

**Comment by abperiasamy** [comment]
Happens frequently. GNU Emacs 24.3.1, go-mode, git-gutter and linum-mode combination.

**Comment by syohex** [comment]
Please upgrade Emacs version Emacs 24.4 or higher.
Emacs 24.3 has a timer bug. This issue may be related to it.
